apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-deployment
  labels:
    app: todolist
spec:
  replicas: 2
  selector:
    matchLabels:
      app: todolist
  template:
    metadata:
      labels:
        app: todolist
    spec:
      containers:
      - name: todolist-container
        image: todolist:newest # Specify your image
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: todolist-service
  labels:
    app: todolist
spec:
  type: NodePort
  selector:
    app: todolist
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 30001 # Optional; Kubernetes will assign a port if omitted
